import { Config, Context, Effect, FileSystem, Layer, PlatformError, Schema } from "effect";
import { configDir, join } from "@tauri-apps/api/path";
import { invoke } from "@tauri-apps/api/core";
import type { OmarchyColors } from "../material/colors";
import { HttpClient } from "effect/unstable/http";

export interface OmarchyThemeImpl {
  clean: () => Effect.Effect<void, PlatformError.PlatformError, never>;
  setTheme: (name: string) => Effect.Effect<void, OmarchyThemeError, never>;
  writeBackgroundImage: (url: URL) => Effect.Effect<void, OmarchyThemeError, never>;
  writeColors: (colors: OmarchyColors) => Effect.Effect<void, OmarchyThemeError, never>;
  writeHyprlandLua: () => Effect.Effect<void, PlatformError.PlatformError, never>;
  writeShell: () => Effect.Effect<void, PlatformError.PlatformError, never>;
}

const imageContentTypeToExtension: Record<string, string> = {
  "image/jpeg": "jpg",
  "image/png": "png",
  "image/webp": "webp",
  "image/gif": "gif",
  "image/avif": "avif",
  "image/bmp": "bmp",
  "image/svg+xml": "svg",
  "image/tiff": "tiff",
};

const imageExtensionFromContentType = (contentType: string | undefined): string => {
  const mimeType = contentType?.split(";")[0]?.trim().toLowerCase();
  return (mimeType && imageContentTypeToExtension[mimeType]) ?? "jpg";
};

export class OmarchyTheme extends Context.Service<OmarchyTheme, OmarchyThemeImpl>()(
  "frontend/features/omarchy-theme/OmarchyTheme",
) {
  static readonly dev = Layer.effect(
    this,
    Effect.gen(function* () {
      const fs = yield* FileSystem.FileSystem;

      const client = (yield* HttpClient.HttpClient).pipe(
        HttpClient.tapRequest((req) => Effect.log(req.toJSON())),
        HttpClient.tap(Effect.log),
        HttpClient.filterStatusOk,
      );

      const home = yield* Effect.promise(configDir);
      const devThemePath = yield* Effect.promise(() => join(home, "omarchy/themes/omaterial-dev"));
      const backgroundImagesPath = yield* Effect.promise(() => join(devThemePath, "backgrounds"));

      yield* fs.makeDirectory(devThemePath, { recursive: true });
      yield* fs.makeDirectory(backgroundImagesPath, { recursive: true });

      const clean: OmarchyThemeImpl["clean"] = () =>
        Effect.gen(function* () {
          yield* Effect.log("Cleaning theme...", devThemePath);
          yield* fs.remove(devThemePath, { recursive: true });
          yield* fs.makeDirectory(devThemePath, { recursive: true });
          yield* fs.makeDirectory(backgroundImagesPath, { recursive: true });
        });

      const setTheme: OmarchyThemeImpl["setTheme"] = (name) =>
        Effect.tryPromise({
          try: () => invoke("set_theme", { name }),
          catch: (cause) => new OmarchyThemeError({ cause }),
        });

      const writeColors: OmarchyThemeImpl["writeColors"] = (colors) =>
        Effect.gen(function* () {
          const colorsTomlPath = yield* Effect.promise(() => join(devThemePath, "colors.toml"));

          const contents = `
# Generated by Omaterial for Omarchy v4.

${Object.entries(colors)
  .map(([key, value]) => `${key} = "${value}"`)
  .join("\n")}
`;
          yield* fs.writeFileString(colorsTomlPath, contents);
        }).pipe(Effect.catch((e) => Effect.fail(new OmarchyThemeError({ cause: e }))));

      const writeBackgroundImage: OmarchyThemeImpl["writeBackgroundImage"] = (url) =>
        Effect.gen(function* () {
          const res = yield* client.get(url.toString());
          const data = yield* res.arrayBuffer;

          const extension = imageExtensionFromContentType(res.headers["content-type"]);

          const imageBytes = new Uint8Array(data);
          const imagePath = yield* Effect.promise(() =>
            join(devThemePath, `backgrounds/background-${crypto.randomUUID()}.${extension}`),
          );

          yield* fs.writeFile(imagePath, imageBytes);
        }).pipe(Effect.catch((e) => Effect.fail(new OmarchyThemeError({ cause: e }))));

      const writeHyprlandLua: OmarchyThemeImpl["writeHyprlandLua"] = () =>
        Effect.gen(function* () {
          const hyprlandLuaPath = yield* Effect.promise(() => join(devThemePath, "hyprland.lua"));

          const contents = `
--
-- Generated by Omaterial for Omarchy v4.
--

hl.config({
  general = {
    gaps_in = 2,
    gaps_out = 4,
    border_size = 1,
  },
  decoration = {
    blur = {
      enabled = true,
      size = 6,
      passes = 3,
      popups = true,
    },
  },
})

-- Bar panels open as the omarchy-keyboard-panel layer; tooltips are popups
-- of omarchy-bar. ignore_alpha keeps the transparent parts unblurred.
hl.layer_rule({
  match = { namespace = "^(omarchy-bar|omarchy-keyboard-panel)$" },
  blur = true,
  blur_popups = true,
  ignore_alpha = 0.2,
})

-- Smart gaps: drop the gaps when only one tiled window is visible.
hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })

-- Drop border and rounding on lone window so it sits flush against the edges.
hl.window_rule({
  match = { float = false, workspace = "w[tv1]" },
  border_size = 0,
  rounding = 0,
})

hl.window_rule({
  match = { float = false, workspace = "f[1]" },
  border_size = 0,
  rounding = 0,
})
`;
          yield* fs.writeFileString(hyprlandLuaPath, contents);
        });

      const writeShell: OmarchyThemeImpl["writeShell"] = () =>
        Effect.gen(function* () {
          const hyprlandLuaPath = yield* Effect.promise(() => join(devThemePath, "shell.toml"));

          const contents = `
# Generated by Omaterial for Omarchy v4.

[popups]
background-alpha = 0.85

`;
          yield* fs.writeFileString(hyprlandLuaPath, contents);
        });

      return { clean, writeColors, writeBackgroundImage, setTheme, writeHyprlandLua, writeShell };
    }),
  );
}

function makeThemeFileWriter(
  fileId: string,
  append = "",
): Effect.Effect<void, OmarchyThemeError, FileSystem.FileSystem> {
  return Effect.gen(function* () {
    const fs = yield* FileSystem.FileSystem;
    const omarchyPath = yield* Config.string("OMARCHY_PATH");
    const tplPath = `${omarchyPath}/default/themed/${fileId}.tpl`;
    const tplExists = yield* fs.exists(tplPath);

    let contents = "";

    if (tplExists) {
      contents = yield* fs.readFileString(tplPath);
    }

    contents += append;
  }).pipe(Effect.catch((error) => new OmarchyThemeError({ cause: error })));
}

export class OmarchyThemeError extends Schema.TaggedError<OmarchyThemeError>()(
  "app/features/omarchy-theme/OmarchyThemeError",
  { cause: Schema.Defect() },
) {}
