import { Context, Effect, FileSystem, Layer, PlatformError } from "effect";
import { configDir, join } from "@tauri-apps/api/path";
import { invoke } from "@tauri-apps/api/core";
import type { OmarchyColors } from "../material/colors";
import { HttpClient } from "effect/unstable/http";
import { OmarchyThemeError, type ThemeFileWriter } from "./shared";
import { writeHyprlandLua } from "./files/hyprland.lua";
import { writeColorsToml } from "./files/colors.toml";

export interface OmarchyThemeImpl {
  clean: () => Effect.Effect<void, PlatformError.PlatformError, never>;
  setTheme: (name: string) => Effect.Effect<void, OmarchyThemeError, never>;
  writeBackgroundImage: (url: URL) => Effect.Effect<void, OmarchyThemeError, never>;
  writeColorsToml: ThemeFileWriter<OmarchyColors>;
  writeHyprlandLua: ThemeFileWriter;
  writeShell: () => Effect.Effect<void, PlatformError.PlatformError, never>;
}

const imageContentTypeToExtension: Record<string, string> = {
  "image/jpeg": "jpg",
  "image/png": "png",
  "image/webp": "webp",
  "image/gif": "gif",
  "image/avif": "avif",
  "image/bmp": "bmp",
  "image/svg+xml": "svg",
  "image/tiff": "tiff",
};

const imageExtensionFromContentType = (contentType: string | undefined): string => {
  const mimeType = contentType?.split(";")[0]?.trim().toLowerCase();
  return (mimeType && imageContentTypeToExtension[mimeType]) ?? "jpg";
};

export class OmarchyTheme extends Context.Service<OmarchyTheme, OmarchyThemeImpl>()(
  "frontend/features/omarchy-theme/OmarchyTheme",
) {
  static readonly dev = Layer.effect(
    this,
    Effect.gen(function* () {
      const fs = yield* FileSystem.FileSystem;

      const client = (yield* HttpClient.HttpClient).pipe(
        HttpClient.tapRequest((req) => Effect.log(req.toJSON())),
        HttpClient.tap(Effect.log),
        HttpClient.filterStatusOk,
      );

      const home = yield* Effect.promise(configDir);
      const devThemePath = yield* Effect.promise(() => join(home, "omarchy/themes/omaterial-dev"));
      const backgroundImagesPath = yield* Effect.promise(() => join(devThemePath, "backgrounds"));

      yield* fs.makeDirectory(devThemePath, { recursive: true });
      yield* fs.makeDirectory(backgroundImagesPath, { recursive: true });

      const clean: OmarchyThemeImpl["clean"] = () =>
        Effect.gen(function* () {
          yield* Effect.log("Cleaning theme...", devThemePath);
          yield* fs.remove(devThemePath, { recursive: true });
          yield* fs.makeDirectory(devThemePath, { recursive: true });
          yield* fs.makeDirectory(backgroundImagesPath, { recursive: true });
        });

      const setTheme: OmarchyThemeImpl["setTheme"] = (name) =>
        Effect.tryPromise({
          try: () => invoke("set_theme", { name }),
          catch: (cause) => new OmarchyThemeError({ cause }),
        });

      const writeBackgroundImage: OmarchyThemeImpl["writeBackgroundImage"] = (url) =>
        Effect.gen(function* () {
          const res = yield* client.get(url.toString());
          const data = yield* res.arrayBuffer;

          const extension = imageExtensionFromContentType(res.headers["content-type"]);

          const imageBytes = new Uint8Array(data);
          const imagePath = yield* Effect.promise(() =>
            join(devThemePath, `backgrounds/background-${crypto.randomUUID()}.${extension}`),
          );

          yield* fs.writeFile(imagePath, imageBytes);
        }).pipe(Effect.catch((e) => Effect.fail(new OmarchyThemeError({ cause: e }))));

      const writeShell: OmarchyThemeImpl["writeShell"] = () =>
        Effect.gen(function* () {
          const hyprlandLuaPath = yield* Effect.promise(() => join(devThemePath, "shell.toml"));

          const contents = `
# Generated by Omaterial for Omarchy v4.

[popups]
background-alpha = 0.85

`;
          yield* fs.writeFileString(hyprlandLuaPath, contents);
        });

      const impl: OmarchyThemeImpl = {
        clean,
        setTheme,
        writeBackgroundImage,
        writeColorsToml: yield* writeColorsToml,
        writeHyprlandLua: yield* writeHyprlandLua,
        writeShell,
      };

      return impl;
    }),
  );
}
