import { Context, Effect, FileSystem, Layer, PlatformError, Schema } from "effect";
import { homeDir, join } from "@tauri-apps/api/path";
import { invoke } from "@tauri-apps/api/core";
import type { OmarchyColors } from "../material/colors";

export interface OmarchyThemeImpl {
  writeColors: (colors: OmarchyColors) => Effect.Effect<void, PlatformError.PlatformError, never>;
  // writeBackgroundImage: (url: URL) => Effect.Effect<void, PlatformError.PlatformError, never>;
  setTheme: (name: string) => Effect.Effect<void, OmarchyThemeError, never>;
}

export class OmarchyTheme extends Context.Service<OmarchyTheme, OmarchyThemeImpl>()(
  "frontend/features/omarchy-theme/OmarchyTheme",
) {
  static readonly dev = Layer.effect(
    this,
    Effect.gen(function* () {
      const fs = yield* FileSystem.FileSystem;
      const home = yield* Effect.promise(homeDir);
      const devThemePath = yield* Effect.promise(() =>
        join(home, ".config/omarchy/themes/omaterial-dev"),
      );

      yield* fs.makeDirectory(devThemePath, { recursive: true });

      const writeColors: OmarchyThemeImpl["writeColors"] = (colors) =>
        Effect.gen(function* () {
          const colorsTomlPath = yield* Effect.promise(() => join(devThemePath, "colors.toml"));

          const contents = `
# Generated by Omaterial for Omarchy v4.

${Object.entries(colors)
  .map(([key, value]) => `${key} = "${value}"`)
  .join("\n")}
`;
          yield* fs.writeFileString(colorsTomlPath, contents);
        });

      const setTheme: OmarchyThemeImpl["setTheme"] = (name) =>
        Effect.tryPromise({
          try: () => invoke("set_theme", { name }),
          catch: (cause) => new OmarchyThemeError({ cause }),
        });

      return { writeColors, setTheme };
    }),
  );
}

export class OmarchyThemeError extends Schema.TaggedError<OmarchyThemeError>()(
  "app/features/omarchy-theme/OmarchyThemeError",
  { cause: Schema.Defect() },
) {}
