packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  "@effect/platform": ^0.97.1
  "@effect/platform-node": ^0.108.1
  "@effect/vitest": "^4.0.0-beta.107"
  "@tauri-apps/api": ^2.11.1
  "@tauri-apps/cli": ^2.11.4
  "@tauri-apps/plugin-fs": ^2.5.1
  "@types/node": ^24.13.3
  effect: "^4.0.0-beta.107"
  electron-vite: ^5.0.0
  typescript: ^7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@0.2.9
  vite-plus: 0.2.9
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
allowBuilds:
  "@parcel/watcher": set this to true or false
  electron: true
  electron-winstaller: true
  esbuild: true
  msgpackr-extract: true
