import type { OmarchyColors } from "@/features/material/colors";
import { makeThemeFileWriter } from "../shared";

export const writeColorsToml = makeThemeFileWriter<OmarchyColors>(
  "colors.toml",
  (colors) => /* toml */ `
# Generated by Omaterial for Omarchy v4.

${Object.entries(colors)
  .map(
    ([key, value]) =>
      `${key} = "${Array.isArray(value) ? (value as string[]).join(" ") : (value as string)}"`,
  )
  .join("\n")}
`,
);
