import type { HyprlandGradient, OmarchyColors } from "@/features/material/colors";
import { makeThemeFileWriter } from "../shared";

export const writeHyprlandLua = makeThemeFileWriter(
  "hyprland.lua",
  (colors: OmarchyColors) => /* lua */ `
--
-- Generated by Omaterial for Omarchy v4.
--

hl.config({
  general = {
    gaps_in = 2,
    gaps_out = 4,
    border_size = 1,
    col = {
      active_border = ${Array.isArray(colors.hyprland_active_border) ? createHyprlandGradient(colors.hyprland_active_border as HyprlandGradient) : `"${colors.hyprland_active_border as string}"`},
      inactive_border = ${Array.isArray(colors.hyprland_inactive_border) ? createHyprlandGradient(colors.hyprland_inactive_border as HyprlandGradient) : `"${colors.hyprland_inactive_border as string}"`},
    },
  },

  group = {
    col = {
      border_active = hyprland_active_border,
      border_inactive = hyprland_inactive_border,
    },
  },

  decoration = {
    blur = {
      enabled = true,
      size = 6,
      passes = 3,
      popups = true,
    },
  },
})

-- Bar panels open as the omarchy-keyboard-panel layer; tooltips are popups
-- of omarchy-bar. ignore_alpha keeps the transparent parts unblurred.
hl.layer_rule({
  match = { namespace = "^(omarchy-bar|omarchy-keyboard-panel)$" },
  blur = true,
  blur_popups = true,
  ignore_alpha = 0.2,
})

-- Smart gaps: drop the gaps when only one tiled window is visible.
hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })

-- Drop border and rounding on lone window so it sits flush against the edges.
hl.window_rule({
  match = { float = false, workspace = "w[tv1]" },
  border_size = 0,
  rounding = 0,
})

hl.window_rule({
  match = { float = false, workspace = "f[1]" },
  border_size = 0,
  rounding = 0,
})

-- ============================================================================
-- >>> OMATERIAL EXPERIMENT: Material 3 window tabs (groupbar) — BEGIN
-- Hand-written on 2026-09-17 to prototype a new tab look. Copy this block into
-- the omaterial hyprland.lua generator once approved, replacing the literal
-- hex values with the matching colors.toml keys (noted per line).
--
-- Design intent (Material 3 "filled tonal" tabs):
--   * Opaque tab pills, no transparency, no blur.
--   * Active tab   = accent (primary) fill, dark_background (on-primary) text.
--   * Inactive tab = lighter_background (surface container) fill,
--                    light_foreground (on-surface-variant) text.
--   * No indicator line under the tabs (indicator_height = 0).
--   * Square-cornered tabs. Gaps are derived from the window gaps:
--       window gap  = general.gaps_out  (== 2 * general.gaps_in, since the
--                     visible gap between two tiled windows is gaps_in on
--                     each side)
--       gap above   = general.border_size  (1px)
--       gap below   = window gap / 2       (2px)
--       gap between = window gap / 2       (2px)
--                     both tighter than the window gaps so the tabs and
--                     the window read as one unit
--     The bar box starts at the window's OUTER edge and overlaps the border,
--     so a gap above of exactly border_size puts the pill top flush with a
--     neighbouring window's content, with the border line visible above the
--     pills (a gap of 0 would paint the pills over the border line). Air
--     around a lone group comes from the general gaps (see the smart-gaps
--     exception above), not from the bar.
-- ============================================================================
-- Inputs: keep in sync with the \`general\` block at the top of this file.
local m3_gaps_in     = 2
local m3_gaps_out    = 4
local m3_border_size = 1

-- Validate the inputs against what Hyprland actually has configured, and the
-- assumption that gaps are uniform (gaps_out == 2 * gaps_in).
do
  local cfg_gaps_in  = hl.get_config("general.gaps_in")
  local cfg_gaps_out = hl.get_config("general.gaps_out")
  local cfg_border   = hl.get_config("general.border_size")
  -- assert(type(cfg_gaps_in) == "table" and cfg_gaps_in.top == m3_gaps_in, "omaterial tabs: m3_gaps_in out of sync with general.gaps_in")
  -- assert(type(cfg_gaps_out) == "table" and cfg_gaps_out.top == m3_gaps_out, "omaterial tabs: m3_gaps_out out of sync with general.gaps_out")
  -- assert(cfg_border == m3_border_size, "omaterial tabs: m3_border_size out of sync with general.border_size")
  -- assert(m3_gaps_out == 2 * m3_gaps_in, "omaterial tabs: gaps_out must equal 2 * gaps_in for the tab gaps to line up")
end

local m3_window_gap    = m3_gaps_out   -- 4
local m3_tab_gap_above = m3_border_size -- 1
local m3_tab_gap_below = m3_window_gap // 2   -- 2
local m3_tab_gap_between = m3_window_gap // 2 -- 2
local m3_tab_active_bg     = "rgb(bcc8d3)"   -- colors.toml: accent
local m3_tab_active_text   = "rgb(131314)"   -- colors.toml: dark_background
local m3_tab_inactive_bg   = "rgb(292a2b)"   -- colors.toml: lighter_background
local m3_tab_inactive_text = "rgb(c8c6c7)"   -- colors.toml: light_foreground
local m3_tab_locked_bg     = "rgb(3d4851)"   -- colors.toml: selection
local m3_tab_locked_dim_bg = "rgb(464748)"   -- colors.toml: muted
local m3_border_active     = "rgb(bcc8d3)"   -- colors.toml: accent
local m3_border_inactive   = "rgb(464748)"   -- colors.toml: muted

hl.config({
  group = {
    groupbar = {
      enabled = true,
      render_titles = true,
      font_size = 11,
      font_family = "monospace",
      font_weight_active = "bold",
      font_weight_inactive = "normal",

      -- Geometry: 24px pills. Hyprland lays the bar out as:
      --   [gaps_out] pill [indicator_gap + indicator_height + gaps_out]
      -- so gaps_out is the gap above and the gap below is topped up with
      -- indicator_gap. Values come from the derivation at the top of the block.
      height = 24,
      gaps_in = m3_tab_gap_between,  -- horizontal gap between tabs (2)
      keep_upper_gap = true,
      gaps_out = m3_tab_gap_above,   -- gap above the pills (1, the border)
      indicator_height = 0,          -- kill the thin line under each tab
      indicator_gap = m3_tab_gap_below - m3_tab_gap_above, -- tops the gap below up to 2

      -- Fill: opaque gradient boxes, square corners.
      gradients = true,
      gradient_rounding = 0,
      gradient_round_only_edges = false,
      round_only_edges = false,
      blur = false,

      text_color = m3_tab_active_text,
      text_color_inactive = m3_tab_inactive_text,
      col = {
        active = m3_tab_active_bg,
        inactive = m3_tab_inactive_bg,
        locked_active = m3_tab_locked_bg,
        locked_inactive = m3_tab_locked_dim_bg,
      },
    },
  },
})
-- <<< OMATERIAL EXPERIMENT: Material 3 window tabs (groupbar) — END
-- ============================================================================
`,
);

const createHyprlandGradient = (gradient: HyprlandGradient) => {
  return `{ colors = { "${gradient[0]}", "${gradient[1]}" }, angle = "${gradient[2]}" }`;
};
