import type { OmarchyColors } from "@/features/material/colors";
import { makeThemeFileWriter } from "../shared";
import { hexFromArgb } from "@material/material-color-utilities";
import { flow } from "effect";

export const writeHyprlandLua = makeThemeFileWriter(
  "hyprland.lua",
  (input: OmarchyColors) => /* lua */ `
--
-- Generated by Omaterial for Omarchy v4.
--

-- Direction the light comes from, in degrees: 0 = right, 90 = top,
-- counter-clockwise. The shadow is cast on the opposite side.
local omaterial_light_angle = 90
local omaterial_shadow_distance = 8
local omaterial_shadow_vector = {
  -math.cos(math.rad(omaterial_light_angle)) * omaterial_shadow_distance,
  math.sin(math.rad(omaterial_light_angle)) * omaterial_shadow_distance, -- screen y points down
}

hl.config({
  general = {
    gaps_in = 2,
    gaps_out = 4,
    -- Gap between the outgoing and incoming workspace while they slide, so
    -- the two read as separate cards.
    gaps_workspaces = 32,
    border_size = 1,
    col = {
      active_border = { colors = { "${flow(hexFromArgb, hexToHyprlandRgb)(input.omaterial_primary)}", "${flow(hexFromArgb, hexToHyprlandRgb)(input.omaterial_outline)}" }, angle = 55 },
      inactive_border = "${flow(hexFromArgb, hexToHyprlandRgb)(input.omaterial_outlineVariant)}"
    },
  },

  decoration = {
    blur = {
      enabled = true,
      size = 6,
      passes = 3,
      popups = true,
      -- Blur everything behind the scratchpad (special workspace).
      special = true,
    },
    shadow = {
      enabled = true,
      color = "${flow(hexFromArgb, (hex) => hex + "4d", hexToHyprlandRgb)(input.omaterial_shadow)}",
      color_inactive = "${flow(hexFromArgb, (hex) => hex + "1a", hexToHyprlandRgb)(input.omaterial_shadow)}",
      range = 60,
      offset = omaterial_shadow_vector,
      render_power = 4,
      scale = 1
    }
  },

  group = {
    col = {
      border_active = { colors = { "${flow(hexFromArgb, hexToHyprlandRgb)(input.omaterial_primary)}", "${flow(hexFromArgb, hexToHyprlandRgb)(input.omaterial_outline)}" }, angle = 55 },
      border_inactive = "${flow(hexFromArgb, hexToHyprlandRgb)(input.omaterial_outlineVariant)}",
    },
    groupbar = {
      enabled = true,
      render_titles = true,
      height = 24,
      gaps_in = 1,
      gaps_out = 2,
      keep_upper_gap = false,
      indicator_height = 0,
      indicator_gap = 0,
      text_padding = 8,

      -- Fill: opaque gradient boxes, square corners.
      gradients = true,
      gradient_rounding = 0,
      gradient_round_only_edges = false,
      round_only_edges = false,
      blur = true,

      text_color = "${flow(hexFromArgb, hexToHyprlandRgb)(input.omaterial_onSecondaryContainer)}",
      text_color_inactive = "${flow(hexFromArgb, hexToHyprlandRgb)(input.omaterial_onSurface)}",
      col = {
        active = "${flow(hexFromArgb, hexToHyprlandRgb)(input.omaterial_secondaryContainer)}",
        inactive = "${flow(hexFromArgb, hexToHyprlandRgb)(input.omaterial_surfaceContainer)}"
      },
    },
  }
})

-- Material 3 motion. Spring tokens from androidx.compose.material3
-- (tokens/StandardMotionTokens.kt, tokens/ExpressiveMotionTokens.kt): mass 1,
-- stiffness, and a damping *ratio*. Hyprland springs take the damping
-- *coefficient*, c = 2 * ratio * sqrt(stiffness * mass). Springs run on
-- physical time, so \`speed\` is required but has no effect.
--
-- Spatial springs move things (position, size), effects springs change
-- colour and opacity. Expressive's spatial springs overshoot (ratio 0.8 is
-- ~1.5%), which on a full-screen slide flashes a strip of wallpaper past the
-- edge, so the workspace slide uses the standard scheme.
local omaterial_motion_schemes = {
  standard = {
    spatial_fast = { stiffness = 1400, ratio = 0.9 },
    spatial_default = { stiffness = 700, ratio = 0.9 },
    spatial_slow = { stiffness = 300, ratio = 0.9 },
    effects_fast = { stiffness = 3800, ratio = 1.0 },
    effects_default = { stiffness = 1600, ratio = 1.0 },
    effects_slow = { stiffness = 800, ratio = 1.0 },
  },
  expressive = {
    spatial_fast = { stiffness = 800, ratio = 0.6 },
    spatial_default = { stiffness = 380, ratio = 0.8 },
    spatial_slow = { stiffness = 200, ratio = 0.8 },
    effects_fast = { stiffness = 3800, ratio = 1.0 },
    effects_default = { stiffness = 1600, ratio = 1.0 },
    effects_slow = { stiffness = 800, ratio = 1.0 },
  },
}
local omaterial_motion_scheme = "standard"

for name, token in pairs(omaterial_motion_schemes[omaterial_motion_scheme]) do
  hl.curve("omaterial_" .. name, {
    type = "spring",
    mass = 1,
    stiffness = token.stiffness,
    dampening = 2 * token.ratio * math.sqrt(token.stiffness),
  })
end

-- Workspaces slide sideways like macOS spaces; the scratchpad drops in from
-- the top. Both settle on the default spatial spring (~300ms for standard).

hl.animation({ leaf = "workspaces", enabled = true, speed = 3, spring = "omaterial_spatial_default", style = "slide" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 3, spring = "omaterial_spatial_default", style = "slidevert" })

-- Every shell surface is its own layer: bar, panels (omarchy-keyboard-panel),
-- notifications, OSD, menu, polkit, clipboard, emojis, reminders. Tooltips
-- and dropdowns are popups of the bar, covered by blur_popups. Each surface
-- paints its card at background-alpha 0.9. Menu-style layers (launcher,
-- clipboard, emojis, polkit) are full-screen with a 0.32 scrim, so
-- ignore_alpha sits between scrim and card: the card blurs, the scrim and
-- the transparent parts do not.

hl.layer_rule({
  match = {
    namespace = "^omarchy-(bar|keyboard-panel|notifications|osd|menu|polkit|clipboard|emojis|reminders)$",
  },
  blur = true,
  blur_popups = true,
  ignore_alpha = 0.5,
})

-- Smart gaps: drop the gaps when a single plain tiled window fills the
-- workspace. A group counts as one tiled window (w[t1]), so w[tg0] (zero
-- tiled groups) is added to keep groups gapped; otherwise the tab bar would
-- sit flush against the top bar.

local omaterial_lone_window = "w[t1] w[tg0]"

hl.workspace_rule({
  workspace = omaterial_lone_window,
  gaps_out = 0,
  gaps_in = 0,
})

hl.workspace_rule({
  workspace = "f[1]",
  gaps_out = 0,
  gaps_in = 0,
})

-- Drop border and rounding on lone window so it sits flush against the edges.
hl.window_rule({
  match = {
    float = false,
    workspace = omaterial_lone_window,
  },
  border_size = 0,
  rounding = 0,
})

hl.window_rule({
  match = { float = false, workspace = "f[1]" },
  border_size = 0,
  rounding = 0,
})
`,
);

const hexToHyprlandRgb = (hex: string) => {
  const code = hex.replace(/^#/, "");
  return code.length === 6 ? `rgb(${code})` : `rgba(${code})`;
};
