import { makeThemeFileWriter } from "../shared";

export const writeHyprlandLua = makeThemeFileWriter(
  "hyprland.lua",
  () => /* lua */ `
--
-- Generated by Omaterial for Omarchy v4.
--

hl.config({
  general = {
    gaps_in = 2,
    gaps_out = 4,
    border_size = 1,
  },
  decoration = {
    blur = {
      enabled = true,
      size = 6,
      passes = 3,
      popups = true,
    },
  },
})

-- Bar panels open as the omarchy-keyboard-panel layer; tooltips are popups
-- of omarchy-bar. ignore_alpha keeps the transparent parts unblurred.
hl.layer_rule({
  match = { namespace = "^(omarchy-bar|omarchy-keyboard-panel)$" },
  blur = true,
  blur_popups = true,
  ignore_alpha = 0.2,
})

-- Smart gaps: drop the gaps when only one tiled window is visible.
hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })

-- Drop border and rounding on lone window so it sits flush against the edges.
hl.window_rule({
  match = { float = false, workspace = "w[tv1]" },
  border_size = 0,
  rounding = 0,
})

hl.window_rule({
  match = { float = false, workspace = "f[1]" },
  border_size = 0,
  rounding = 0,
})

`,
);
