import type { OmarchyColors } from "@/features/material/colors";
import { makeThemeFileWriter } from "../shared";
import { hexFromArgb } from "@material/material-color-utilities";

export const writeShellBarToml = makeThemeFileWriter<OmarchyColors>(
  "shell.bar.toml",
  (input) => /* toml */ `
# Generated by Omaterial for Omarchy v4.

background       = "${hexFromArgb(input.omaterial_secondaryContainer)}"
background-alpha = 0.9
text             = "${hexFromArgb(input.omaterial_onSecondaryContainer)}"
active           = "${input.red}"
`,
);

export const writeShellHyprlandToml = makeThemeFileWriter<OmarchyColors>(
  "shell.hyprland.toml",
  (input) => /* toml */ `
# Generated by Omaterial for Omarchy v4.

# Shared Hyprland-derived border tokens. Surface sections reference these so
# lock, notifications, popups, and menu-style cards stay aligned with the
# current Hyprland active-border gradient.

active-border            = "${hexFromArgb(input.omaterial_primary)} ${hexFromArgb(input.omaterial_outline)} 55deg"
active-border-foreground = "${hexFromArgb(input.omaterial_outline)}"
`,
);

export const writeShellControlsToml = makeThemeFileWriter<OmarchyColors>(
  "shell.controls.toml",
  (input) => /* toml */ `
# Generated by Omaterial for Omarchy v4.

# Shared state tokens for interactive control chrome (buttons, dropdowns,
# tab strips, etc).
#
# The shell paints each state as <color> at <fill-alpha> over the card, and
# draws labels in the foreground (or in selected-color when selected). That
# is Material 3's state layer model, so the fills stay translucent: an opaque
# fill would sit under same-colored text. State layer opacities follow M3
# (hover 8%, focus 10%, pressed 10%, dragged/selected 16%).

# Normal: idle control chrome. Border widths accept one CSS-style scalar/list:
# N, "Y X", "T X B", or "T R B L". Per-side keys like
# normal-border-width-left override the list. Each *-border accepts either a
# solid color or a Hyprland-style gradient, e.g. "rgba(...) rgba(...) 45deg".
# M3 outlined control at rest: no state layer, 1px outline.
normal-color        = "${hexFromArgb(input.omaterial_onSurface)}"
normal-fill-alpha   = 0
normal-border       = "${hexFromArgb(input.omaterial_outline)}"
normal-border-width = 1
normal-border-alpha = 1.0

# Hover-cursor: mouse hover and the panel keyboard cursor.
# M3 hover: on-surface state layer at 8%, outline unchanged.
hover-cursor-color        = "${hexFromArgb(input.omaterial_onSurface)}"
hover-cursor-fill-alpha   = 0.08
hover-cursor-border       = "${hexFromArgb(input.omaterial_outline)}"
hover-cursor-border-width = 1
hover-cursor-border-alpha = 1.0

# Focus: Qt activeFocus.
# M3 focus: on-surface state layer at 10%, outline switches to primary.
focus-color        = "${hexFromArgb(input.omaterial_onSurface)}"
focus-fill-alpha   = 0.10
focus-border       = "${hexFromArgb(input.omaterial_primary)}"
focus-border-width = 1
focus-border-alpha = 1.0

# Selected: persistent chosen/current state. selected-color doubles as the
# label color, so it must read as text on its own tint.
# M3 selected: primary label over a primary state layer at 16%, no border.
selected-color        = "${hexFromArgb(input.omaterial_primary)}"
selected-fill-alpha   = 0.16
selected-border       = "${hexFromArgb(input.omaterial_primary)}"
selected-border-width = 0
selected-border-alpha = 1.0

# Momentary fills.
# M3 pressed: on-surface state layer at 10%.
pressed-color        = "${hexFromArgb(input.omaterial_onSurface)}"
pressed-fill-alpha   = 0.10
# M3 text selection: primary at 40%; selected text keeps the foreground.
selection-color      = "${hexFromArgb(input.omaterial_primary)}"
selection-fill-alpha = 0.40
`,
);

export const writeShellSpacingToml = makeThemeFileWriter(
  "shell.spacing.toml",
  () => /* toml */ `
# Generated by Omaterial for Omarchy v4.

# \`scale\` multiplies shared margins, gaps, padding, controls, and panel
# dimensions; components keep their proportions. With scale-with-font
# enabled, those dimensions grow/shrink with [font] base-size too. Per-token
# overrides (in px) below pin individual values without affecting the rest
# of the scale. Uncomment any to tune a specific surface.
#
# Left unpinned on purpose. A pinned token is absolute px and skips both
# scale and font scaling. The defaults already sit on Material 3's 8dp
# rhythm once you account for the shell's 12px base font (M3 sizes assume
# 14sp): 8dp = 7px, 16dp = 14px, 24dp = 20px, and control-height 28 equals an
# M3 button at maximum density.

scale = 1.0
scale-with-font = true
# xxs                       = 2
# xs                        = 3
# sm                        = 4
# md                        = 6
# lg                        = 8
# xl                        = 10
# xxl                       = 12
# xxxl                      = 14
# huge                      = 18
# control-gap               = 8
# control-padding-x         = 10
# control-padding-y         = 6
# input-padding-y           = 7
# control-height            = 28
# popup-row-height          = 28
# row-gap                   = 8
# row-padding-x             = 12
# label-gap                 = 4
# panel-gap                 = 14
# panel-padding             = 18
# popup-padding             = 14
# dropdown-width            = 240
# searchable-dropdown-width = 260
# number-field-width        = 120
# searchable-popup-min-height = 220
`,
);

export const writeShellPopupsToml = makeThemeFileWriter<OmarchyColors>(
  "shell.popups.toml",
  (input) => /* toml */ `
# Generated by Omaterial for Omarchy v4.

# Shared by every bar flyout (dropdowns, OSD, popup cards).
# Border accepts either a solid color or a Hyprland-style gradient. Border
# widths accept one CSS-style scalar/list: N, "Y X", "T X B", or "T R B L";
# individual border-width-top/right/bottom/left keys override the list.
#
# M3 menu / popup container: surface-container with on-surface text. Menus
# carry no accent edge, so the border is the 1px outline-variant of an M3
# outlined card, matching Hyprland's inactive border. background-alpha
# matches the bar so the blur layer rule in hyprland.lua treats both alike.

background       = "${hexFromArgb(input.omaterial_surfaceContainer)}"
background-alpha = 0.9
text             = "${hexFromArgb(input.omaterial_onSurface)}"
border           = "${hexFromArgb(input.omaterial_outlineVariant)}"
border-alpha     = 1.0
border-width     = 1
`,
);

export const writeShellTooltipsToml = makeThemeFileWriter<OmarchyColors>(
  "shell.tooltip.toml",
  (input) => /* toml */ `
# Generated by Omaterial for Omarchy v4.

# Hover tooltips across the bar, panels, and buttons.
#
# M3 plain tooltip: inverse-surface container with inverse-on-surface label,
# no outline. border-width 0 drops the shell's default 1px edge; border is
# kept as the text color so any instance that forces a width still reads
# correctly. background-alpha 0.9 lets the blur layer rule show through.

background       = "${hexFromArgb(input.omaterial_inverseSurface)}"
background-alpha = 0.9
text             = "${hexFromArgb(input.omaterial_inverseOnSurface)}"
border           = "${hexFromArgb(input.omaterial_inverseOnSurface)}"
border-alpha     = 1.0
border-width     = 0
`,
);

export const writeShellFontToml = makeThemeFileWriter(
  "shell.font.toml",
  () => /* toml */ `
# Generated by Omaterial for Omarchy v4.

# base-size is the rem root for the type scale. Every Style.font.<token>
# derives from it (e.g. body = base, subtitle ≈ base * 1.083,
# heading ≈ base * 1.333). The shell only floors this at 1px; increase it
# as much as you want.
#
# Left unpinned. The shell's ratios already track the M3 type scale
# (label 11/12, body 12/14, title 14/16, headline 24, display 28+) once the
# root is set, and a pinned token stops following base-size.

base-size = 12
# caption       = 10
# body-small    = 11
# body          = 12
# subtitle      = 13
# title         = 14
# heading       = 16
# display       = 24
# display-large = 28
# icon-small    = 11
# icon          = 14
# icon-large    = 18
`,
);

export const writeShellNotificationsToml = makeThemeFileWriter<OmarchyColors>(
  "shell.notifications.toml",
  (input) => /* toml */ `
# Generated by Omaterial for Omarchy v4.

# M3 floating card: surface-container-high with on-surface text. The border
# keeps the Omarchy convention of matching the Hyprland active window
# (primary to outline, 55deg) since a notification is an attention surface.
# countdown is the progress ring; primary is M3's indicator color.
# background-alpha 0.9 lets the blur layer rule show through.

background       = "${hexFromArgb(input.omaterial_surfaceContainerHigh)}"
background-alpha = 0.9
text             = "${hexFromArgb(input.omaterial_onSurface)}"
border           = "${hexFromArgb(input.omaterial_primary)} ${hexFromArgb(input.omaterial_outline)} 55deg"
border-alpha     = 1.0
border-width     = 1
countdown        = "${hexFromArgb(input.omaterial_primary)}"
`,
);

// [launcher] and [menu] share the same six tokens; the installed shell only
// reads [menu] today, but the template still ships [launcher] so it is
// emitted with identical values.
const menuLikeSection = (input: OmarchyColors) => /* toml */ `
# M3 dialog card: surface-container-high with on-surface text and no
# outline; the scrim, alpha and blur give it definition. scrim is M3's
# scrim role at 32%. The selected row is an M3 selected list item:
# secondary-container fill with on-secondary-container text and no extra
# border (alpha 0). background-alpha 0.9 lets the blur layer rule show
# through. border-width 0 also sidesteps Qt rasterising a 1px border as
# 2px at fractional display scales.

background                = "${hexFromArgb(input.omaterial_surfaceContainerHigh)}"
background-alpha          = 0.9
text                      = "${hexFromArgb(input.omaterial_onSurface)}"
border                    = "${hexFromArgb(input.omaterial_outlineVariant)}"
border-alpha              = 1.0
border-width              = 0
scrim                     = "${hexFromArgb(input.omaterial_scrim)}"
scrim-alpha               = 0.32
selected-background       = "${hexFromArgb(input.omaterial_secondaryContainer)}"
selected-background-alpha = 1.0
selected-text             = "${hexFromArgb(input.omaterial_onSecondaryContainer)}"
selected-border           = "${hexFromArgb(input.omaterial_secondaryContainer)}"
selected-border-alpha     = 0
`;

export const writeShellLauncherToml = makeThemeFileWriter<OmarchyColors>(
  "shell.launcher.toml",
  (input) => /* toml */ `
# Generated by Omaterial for Omarchy v4.

# Same six tokens as [menu], applied to the launcher overlay.
${menuLikeSection(input)}`,
);

export const writeShellMenuToml = makeThemeFileWriter<OmarchyColors>(
  "shell.menu.toml",
  (input) => /* toml */ `
# Generated by Omaterial for Omarchy v4.

# Cards, rows, and selected-row treatment. Clipboard and emojis inherit
# these tokens.
${menuLikeSection(input)}`,
);

export const writeShellPolkitToml = makeThemeFileWriter<OmarchyColors>(
  "shell.polkit.toml",
  (input) => /* toml */ `
# Generated by Omaterial for Omarchy v4.

# Polkit authentication prompt (sudo/password dialogs).
# M3 dialog: surface-container-high card, on-surface text, no outline
# (border-width 0, like [menu]), scrim at 32%. Error states use the M3
# error role for both the text and the border colour, should a width be
# set. accent is the lock-icon glyph and text-selection tint.
# background-alpha 0.9 lets the blur layer rule show through.

background       = "${hexFromArgb(input.omaterial_surfaceContainerHigh)}"
background-alpha = 0.9
text             = "${hexFromArgb(input.omaterial_onSurface)}"
text-error       = "${hexFromArgb(input.omaterial_error)}"
border           = "${hexFromArgb(input.omaterial_outlineVariant)}"
border-error     = "${hexFromArgb(input.omaterial_error)}"
border-alpha     = 1.0
border-width     = 0
scrim            = "${hexFromArgb(input.omaterial_scrim)}"
scrim-alpha      = 0.32
accent           = "${hexFromArgb(input.omaterial_primary)}"
`,
);

export const writeShellLockToml = makeThemeFileWriter<OmarchyColors>(
  "shell.lock.toml",
  (input) => /* toml */ `
# Generated by Omaterial for Omarchy v4.

# Lock screen password input.
# M3 outlined text field: surface-container-highest container, on-surface
# text, on-surface-variant placeholder, outline at rest, primary when
# active, error when wrong. Slightly translucent so the wallpaper shows
# through, matching the bar. selection is primary at 40% like [controls].

background       = "${hexFromArgb(input.omaterial_surfaceContainerHighest)}"
background-alpha = 0.9
text             = "${hexFromArgb(input.omaterial_onSurface)}"
placeholder      = "${hexFromArgb(input.omaterial_onSurfaceVariant)}"
text-error       = "${hexFromArgb(input.omaterial_error)}"
border           = "${hexFromArgb(input.omaterial_outline)}"
border-active    = "${hexFromArgb(input.omaterial_primary)}"
border-error     = "${hexFromArgb(input.omaterial_error)}"
border-alpha     = 1.0
# The shell hardcodes a 3px outline unless a width is given; 1px matches
# the Hyprland border and the popups.
border-width     = 1
selection        = "${hexFromArgb(input.omaterial_primary)}"
selection-alpha  = 0.40
`,
);

export const writeShellImagePickerToml = makeThemeFileWriter<OmarchyColors>(
  "shell.image-picker.toml",
  (input) => /* toml */ `
# Generated by Omaterial for Omarchy v4.

# Carousel-style picker. There is no card, so text sits directly on the
# scrim; the scrim therefore uses the theme background (mode-aware) rather
# than M3's always-dark scrim, keeping on-surface text readable in both
# light and dark schemes. selected slice: primary. unselected: outline.

scrim                   = "${hexFromArgb(input.omaterial_background)}"
scrim-alpha             = 0.5
text                    = "${hexFromArgb(input.omaterial_onSurface)}"
selected-border         = "${hexFromArgb(input.omaterial_primary)}"
selected-border-alpha   = 1.0
unselected-border       = "${hexFromArgb(input.omaterial_outline)}"
unselected-border-alpha = 1.0
`,
);
