import type { OmarchyColors } from "@/features/material/colors";
import { makeThemeFileWriter } from "../shared";
import { hexFromArgb } from "@material/material-color-utilities";

export const writeShellBarToml = makeThemeFileWriter<OmarchyColors>(
  "shell.bar.toml",
  (input) => /* toml */ `
# Generated by Omaterial for Omarchy v4.

# Alpha companions (where present) range from 0 (invisible) to 1 (opaque).
background       = "${hexFromArgb(input.omaterial_secondaryContainer)}"
background-alpha = 0.9
text             = "${hexFromArgb(input.omaterial_onSecondaryContainer)}"
# Modules calling attention to themselves (recording, voxtype, alerts, updates)
active           = "${input.red}"
# Cross-axis size at font base-size 12. size-horizontal is the height of
# top/bottom bars; size-vertical is the width of left/right bars. With
# scale-with-font enabled, these grow/shrink with [font] base-size.
scale-with-font  = true
size-horizontal  = 26
size-vertical    = 28
`,
);
