import type { OmarchyColors } from "@/features/material/colors";
import { makeThemeFileWriter } from "../shared";

export const writeShellBarToml = makeThemeFileWriter<OmarchyColors>(
  "shell.bar.toml",
  (_input) => /* toml */ `
# Generated by Omaterial for Omarchy v4.


`,
);
